module.exports = {
    rules: {
        // Possible Errors
        'no-cond-assign': [2, 'except-parens'],
        'no-console': [1, { allow: ['warn', 'error'] }],
        'no-constant-condition': [2],
        'no-control-regex': [2],
        'no-debugger': [1],
        'no-dupe-args': [1],
        'no-dupe-keys': [1],
        'no-duplicate-case': [1],
        'no-empty-character-class': [2],
        'no-empty': [1, { allowEmptyCatch: true }],
        'no-ex-assign': [2],
        'no-func-assign': [2],
        'no-inner-declarations': [1],
        'no-invalid-regexp': [2],
        'no-irregular-whitespace': [2],
        'no-obj-calls': [2],
        'no-regex-spaces': [1],
        'no-sparse-arrays': [1],
        'no-unexpected-multiline': [1],
        'no-unreachable': [1],
        'no-unsafe-finally': [1],
        'no-unsafe-negation': [2],
        'use-isnan': [2],
        'valid-typeof': [1],

        // Best Practices
        'array-callback-return': [2],
        'block-scoped-var': [2],
        'dot-notation': [1, { allowKeywords: true }],
        'eqeqeq': [1, 'always'],
        'no-alert': [1],
        'no-caller': [2],
        'no-case-declarations': [1],
        'no-div-regex': [1],
        'no-empty-function': [1],
        'no-eq-null': [1],
        'no-eval': [1],
        'no-floating-decimal': [1],
        'no-global-assign': [1],
        'no-implied-eval': [1],
        'no-iterator': [1],
        'no-labels': [1],
        'no-multi-spaces': [1],
        'no-multi-str': [1],
        'no-new-func': [1],
        'no-new-wrappers': [2],
        'no-octal-escape': [1],
        'no-octal': [2],
        'no-proto': [1],
        'no-redeclare': [2],
        'no-script-url': [1],
        'no-self-assign': [2],
        'no-self-compare': [2],
        'no-sequences': [2],
        'no-throw-literal': [1],
        'no-unmodified-loop-condition': [1],
        'no-unused-expressions': [1, { allowShortCircuit: true, allowTernary: true }],
        'no-unused-labels': [2],
        'no-useless-call': [1],
        'no-useless-concat': [1],
        'no-useless-escape': [2],
        'no-with': [2],
        'wrap-iife': [1, 'inside'],

        // Variables
        'no-catch-shadow': [1],
        'no-delete-var': [2],
        'no-label-var': [1],
        'no-shadow-restricted-names': [2],
        'no-undef': [2],
        'no-unused-vars': [1, { args: 'none' }],
        'no-use-before-define': [1, { functions: false }],

        // Node.js and CommonJS
        'no-new-require': [2],

        // Stylistic Issues
        "semi": [1, 'always', { omitLastInOneLineBlock: false }],
    },
};
